[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = '0.8.30'
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200
viaIR = true

[rpc_endpoints]
# All available network keywords:
# https://github.com/foundry-rs/forge-std/blob/ff4bf7db008d096ea5a657f2c20516182252a3ed/src/StdCheats.sol#L255-L271
arbitrum_one = "${ARBITRUM_ONE_RPC_URL}"
bnb_smart_chain = "${BSC_RPC_URL}"
base = "${BASE_RPC_URL}"

[fmt]
# Line formatting
line_length = 120
tab_width = 4
wrap_comments = true

# Statement blocks formatting
single_line_statement_blocks = "single"

# Function header formatting
multiline_func_header = "params_first"

# Import organization
sort_imports = true

# Contract spacing
contract_new_lines = true

# Override spacing
override_spacing = true

# Bracket spacing
bracket_spacing = false

# Type formatting
int_types = "long"

# Quote style
quote_style = "double"

# Number formatting
number_underscore = "thousands"
hex_underscore = "remove"

# Files to ignore during formatting
ignore = ["lib/", "script/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
